spring.application.name=FoodiMap
server.port=8080

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

jwt.secret=41Kpj9RCdn2+6N2pkPz5CkzVkUgE/2ctdu/iStcCTYFn+DsP0l9kHYt9lyK6JUmflemcVm9dPwqDylrYxFWu7Q==
  jwt.expiration=86400000
# 86400000 milliseconds = 24 hours

logging.level.org.springframework.security=DEBUG

frontend.url="http://localhost:5173"

upload.path=""